name: selec. Backend Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Update the env file with secrets
    - name: 'Create env file'
      run: |
        touch config.env
        echo ATLAS_URI=${{ secrets.ATLAS_URI }} >> config.env
        echo PORT=3000 >> config.env
        echo "Printing repo contents"
        ls -la
        echo "Printing repo contents"
        cat config.env
    
    # - name: Test
    #   run: npm test

    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: build_push
      env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
      run: |
          docker \ 
            --build-arg ATLAS_URI=$ATLAS_URI
          build .
      with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/review-portal-backend:latest
          
    - name: Image ID
      run: echo ${{ steps.build_push.outputs.imageid }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./.github/actions/ansible
      env:
        SSH_PASS: ${{ secrets.ANSIBLE_SSH_PASSWORD }}
        AZUREVM_IP_ADDRESS: ${{ secrets.AZUREVM_IP_ADDRESS }}